export let en = {
    "Backquote": {
        "onShift": "`",
        "activShift": "~",
    },
    "Digit1": {
        "onShift": "1",
        "activShift": "!",
    },
    "Digit2": {
        "onShift": "2",
        "activShift": "@",
    },
    "Digit3": {
        "onShift": "3",
        "activShift": "#",
    },
    "Digit4": {
        "onShift": "4",
        "activShift": "$",
    },
    "Digit5": {
        "onShift": "5",
        "activShift": "%",
    },
    "Digit6": {
        "onShift": "6",
        "activShift": "^",
    },
    "Digit7": {
        "onShift": "7",
        "activShift": "&",
    },
    "Digit8": {
        "onShift": "8",
        "activShift": "*",
    },
    "Digit9": {
        "onShift": "9",
        "activShift": "(",
    },
    "Digit0": {
        "onShift": "0",
        "activShift": ")",
    },
    "Minus": {
        "onShift": "-",
        "activShift": "_",
    },
    "Equal": {
        "onShift": "=",
        "activShift": "+",
    },
    "Backspace": "Backspace",
    "Tab": "Tab",
    "KeyQ": "q",
    "KeyW": "w",
    "KeyE": "e",
    "KeyR": "r",
    "KeyT": "t",
    "KeyY": "y",
    "KeyU": "u",
    "KeyI": "i",
    "KeyO": "o",
    "KeyP": "p",
    "BracketLeft": "[",
    "BracketRight": "]",
    "Backslash": "\\",
    "Delete": "Delete",
    "CapsLock": "CapsLock",
    "KeyA": "a",
    "KeyS": "s",
    "KeyD": "d",
    "KeyF": "f",
    "KeyG": "g",
    "KeyH": "h",
    "KeyJ": "j",
    "KeyK": "k",
    "KeyL": "l",
    "Semicolon": ";",
    "Quote": "'",
    "Enter": "Enter",
    "ShiftLeft": "Shift",
    "KeyZ": "z",
    "KeyX": "x",
    "KeyC": "c",
    "KeyV": "v",
    "KeyB": "b",
    "KeyN": "n",
    "KeyM": "m",
    "Comma": ",",
    "Period": ".",
    "Slash": "/",
    "ArrowUp": "🠕",
    "ShiftRight": "Shift",
    "ControlLeft": "Control",
    "MetaLeft": "Meta",
    "AltLeft": "Alt",
    "AltRight": "Alt",
    "ArrowLeft": "🠔",
    "ArrowDown": "🠗",
    "ArrowRight": "🠖",
    "ControlRight": "Control",
    "Space": "Space",
}

export let ru = {
    "Backquote": "ё",
    "Digit1": {
        "activShift": "!",
        "onShift": "1",
    },
    "Digit2": {
        "activShift": ",",
        "onShift": "2",
    },
    "Digit3": {
        "activShift": "№",
        "onShift": "3",
    },
    "Digit4": {
        "activShift": ";",
        "onShift": "4",
    },
    "Digit5": {
        "activShift": "%",
        "onShift": "5",
    },
    "Digit6": {
        "activShift": ":",
        "onShift": "6",
    },
    "Digit7": {
        "activShift": "?",
        "onShift": "7",
    },
    "Digit8": {
        "activShift": "*",
        "onShift": "8",
    },
    "Digit9": {
        "activShift": "(",
        "onShift": "9",
    },
    "Digit0": {
        "activShift": ")",
        "onShift": "0",
    },
    "Minus": {
        "activShift": "_",
        "onShift": "-",
    },
    "Equal": {
        "activShift": "+",
        "onShift": "=",
    },
    "Backspace": "Backspace",
    "Tab": "Tab",
    "KeyQ": "й",
    "KeyW": "ц",
    "KeyE": "у",
    "KeyR": "к",
    "KeyT": "е",
    "KeyY": "н",
    "KeyU": "г",
    "KeyI": "ш",
    "KeyO": "щ",
    "KeyP": "з",
    "BracketLeft": "х",
    "BracketRight": "ъ",
    "Backslash": "\\",
    "Delete": "Delete",
    "CapsLock": "CapsLock",
    "KeyA": "ф",
    "KeyS": "ы",
    "KeyD": "в",
    "KeyF": "а",
    "KeyG": "п",
    "KeyH": "р",
    "KeyJ": "о",
    "KeyK": "л",
    "KeyL": "д",
    "Semicolon": "ж",
    "Quote": "э",
    "Enter": "Enter",
    "ShiftLeft": "Shift",
    "KeyZ": "я",
    "KeyX": "ч",
    "KeyC": "с",
    "KeyV": "м",
    "KeyB": "и",
    "KeyN": "т",
    "KeyM": "ь",
    "Comma": "б",
    "Period": "ю",
    "Slash": ".",
    "ShiftRight": "Shift",
    "ControlLeft": "Control",
    "MetaLeft": "Meta",
    "AltLeft": "Alt",
    "AltRight": "Alt",
    "ArrowLeft": "🠔",
    "ArrowUp": "🠕",
    "ArrowDown": "🠗",
    "ArrowRight": "🠖",
    "ControlRight": "Control",
    "Space": "Space",
}

export let ID = [
    "Backquote",
    "Digit1",
    "Digit2",
    "Digit3",
    "Digit4",
    "Digit5",
    "Digit6",
    "Digit7",
    "Digit8",
    "Digit9",
    "Digit0",
    "Minus",
    "Equal",
    "Backspace",
    "Tab",
    "KeyQ",
    "KeyW",
    "KeyE",
    "KeyR",
    "KeyT",
    "KeyY",
    "KeyU",
    "KeyI",
    "KeyO",
    "KeyP",
    "BracketLeft",
    "BracketRight",
    "Backslash",
    "Delete",
    "CapsLock",
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyG",
    "KeyH",
    "KeyJ",
    "KeyK",
    "KeyL",
    "Semicolon",
    "Quote",
    "Enter",
    "ShiftLeft",
    "KeyZ",
    "KeyX",
    "KeyC",
    "KeyV",
    "KeyB",
    "KeyN",
    "KeyM",
    "Comma",
    "Period",
    "Slash",
    "ArrowUp",
    "ShiftRight",
    "ControlLeft",
    "MetaLeft",
    "AltLeft",
    "Space",
    "AltRight",
    "ArrowLeft",
    "ArrowDown",
    "ArrowRight",
    "ControlRight"
]